version: '3.2'
services:
    kernel-builder:
        build: 
            context: ./kiln/api
            dockerfile: Dockerfile.kernel-builder
        volumes:
            - kernel-data:/output

    rootfs-builder:
        build: 
            context: ./kiln/api
            dockerfile: Dockerfile.rootfs-builder
        privileged: true
        cap_add:
            - SYS_ADMIN
            - MKNOD
        security_opt:
            - apparmor:unconfined
            - seccomp:unconfined
        devices:
            - /dev/loop-control
            - /dev/loop0
            - /dev/loop1
            - /dev/loop2
            - /dev/loop3
            - /dev/loop4
            - /dev/loop5
            - /dev/loop6
            - /dev/loop7
        volumes:
            - rootfs-data:/output

    api:
        build: ./kiln/api/.
        container_name: kiln_api
        restart: unless-stopped
        cgroup: host
        stop_grace_period: 10s
        stop_signal: SIGTERM
        privileged: true
        volumes:
            - ./data/kiln/packages:/kiln/packages
            - kernel-data:/var/lib/firecracker/kernels
            - rootfs-data:/var/lib/firecracker/rootfs
        environment:
            - kiln_DISABLE_NETWORKING=false
            - kiln_RUN_TIMEOUT=300000
            - kiln_REPO_URL=http://kiln_repo:8000/index
            - kiln_LOG_LEVEL=DEBUG
            - kiln_MAX_FILE_SIZE=500000000 # 500 MB
            - kiln_PROXY_DOMAIN=https://code-proxy.frohrer.com
        ports:
            - "2000:2000"
            - "2020:2020"
        networks:
            - kiln-network
        depends_on:
            kernel-builder:
                condition: service_completed_successfully
            rootfs-builder:
                condition: service_completed_successfully
    # repo:
    #     build: ./kiln/repo/.
    #     container_name: kiln_repo
    #     privileged: true
    #     ports:
    #         - "8000:8000"
    #     networks:
    #         - kiln-network
    #     volumes:
    #         - kiln_repo_data:/app/packages
    ui:
        build: ./ui/
        container_name: kiln_ui
        environment:
            - API_BASE=http://kiln_api:2000/api/v2
        ports:
            - "8080:5000"
        networks:
            - kiln-network

networks:
    kiln-network:
        driver: bridge

volumes:
    kiln_repo_data:
    kernel-data:
        driver: local
    rootfs-data:
        driver: local
