version: '3.2'
services:
    kernel-builder:
        build: 
            context: .
            dockerfile: kiln/api/Dockerfile.kernel-builder
        volumes:
            - kernel-data:/output

    rootfs-builder:
        build: 
            context: .
            dockerfile: kiln/api/Dockerfile.rootfs-builder
        privileged: true
        volumes:
            - rootfs-data:/output

    api:
        build: 
            context: .
            dockerfile: kiln/api/Dockerfile
        container_name: kiln_api
        restart: unless-stopped
        cgroup: host
        stop_grace_period: 10s
        stop_signal: SIGTERM
        privileged: true
        devices:
            - /dev/kvm:/dev/kvm
        volumes:
            - ./data/kiln/packages:/kiln/packages
            - kernel-data:/var/lib/firecracker/kernels
            - rootfs-data:/var/lib/firecracker/rootfs
            - firecracker-images:/var/lib/firecracker/images
        environment:
            - kiln_DISABLE_NETWORKING=false
            - kiln_RUN_TIMEOUT=300000
            - kiln_REPO_URL=http://kiln_repo:8000/index
            - kiln_LOG_LEVEL=DEBUG
            - kiln_MAX_FILE_SIZE=500000000 # 500 MB
            - kiln_PROXY_DOMAIN=https://code-proxy.frohrer.com
            - NODE_ENV=development
            - PORT=3000
            - FIRECRACKER_PATH=/usr/local/bin/firecracker
        ports:
            - "3000:3000"
            - "80:80"  # Firecracker API port
            - "2000:2000"
            - "2020:2020"
        networks:
            - kiln-network
        depends_on:
            kernel-builder:
                condition: service_completed_successfully
            rootfs-builder:
                condition: service_completed_successfully
        cap_add:
            - ALL
    # repo:
    #     build: ./kiln/repo/.
    #     container_name: kiln_repo
    #     privileged: true
    #     ports:
    #         - "8000:8000"
    #     networks:
    #         - kiln-network
    #     volumes:
    #         - kiln_repo_data:/app/packages
    ui:
        build: ./ui/
        container_name: kiln_ui
        environment:
            - API_BASE=http://kiln_api:2000/api/v2
        ports:
            - "8080:5000"
        networks:
            - kiln-network

networks:
    kiln-network:
        driver: bridge

volumes:
    kiln_repo_data:
    kernel-data:
        driver: local
    rootfs-data:
        driver: local
    firecracker-images:
        driver: local
