FROM debian:buster-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y git build-essential bc flex bison libelf-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /build

# Clone and build Linux kernel
RUN set -e && \
    git clone --depth 1 --branch v5.10 https://github.com/torvalds/linux.git linux.git && \
    cd linux.git && \
    # Basic kernel config for Firecracker
    echo 'CONFIG_SERIAL_8250=y' > .config && \
    echo 'CONFIG_SERIAL_8250_CONSOLE=y' >> .config && \
    echo 'CONFIG_EXT4_FS=y' >> .config && \
    echo 'CONFIG_VIRTIO_BLK=y' >> .config && \
    echo 'CONFIG_VIRTIO_NET=y' >> .config && \
    echo 'CONFIG_VIRTIO=y' >> .config && \
    echo 'CONFIG_VIRTIO_PCI=y' >> .config && \
    echo 'CONFIG_VIRTIO_MMIO=y' >> .config && \
    echo 'CONFIG_NET_9P=y' >> .config && \
    echo 'CONFIG_NET_9P_VIRTIO=y' >> .config && \
    echo 'CONFIG_9P_FS=y' >> .config && \
    echo 'CONFIG_SQUASHFS=y' >> .config && \
    echo 'CONFIG_SQUASHFS_XZ=y' >> .config && \
    echo 'CONFIG_DEVTMPFS=y' >> .config && \
    echo 'CONFIG_CGROUPS=y' >> .config && \
    echo 'CONFIG_INOTIFY_USER=y' >> .config && \
    echo 'CONFIG_SIGNALFD=y' >> .config && \
    echo 'CONFIG_TIMERFD=y' >> .config && \
    echo 'CONFIG_EPOLL=y' >> .config && \
    echo 'CONFIG_NR_CPUS=1' >> .config && \
    echo 'CONFIG_EMBEDDED=y' >> .config && \
    echo 'CONFIG_SYSFS=y' >> .config && \
    echo 'CONFIG_PROC_FS=y' >> .config && \
    echo 'CONFIG_NAMESPACES=y' >> .config && \
    echo 'CONFIG_UNIX=y' >> .config && \
    echo 'CONFIG_POSIX_MQUEUE=y' >> .config && \
    echo 'CONFIG_FUTEX=y' >> .config && \
    echo 'CONFIG_SHMEM=y' >> .config && \
    echo 'CONFIG_PRINTK=y' >> .config && \
    echo 'CONFIG_BUG=y' >> .config && \
    echo 'CONFIG_PCIEPORTBUS=y' >> .config && \
    echo 'CONFIG_PCI_MSI=y' >> .config && \
    echo 'CONFIG_DEBUG_KERNEL=n' >> .config && \
    echo 'CONFIG_SMP=n' >> .config && \
    make olddefconfig && \
    make -j$(nproc) vmlinux

VOLUME /output
CMD cp linux.git/vmlinux /output/vmlinux 